# Generated by Django 3.2 on 2023-03-29 21:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INDIVIDU', 'INDIVIDU'), ('GROUPE', 'GROUP')], default=utils.enums.VictimTypeEnum['INDIVIDU'], max_length=200)),
                ('name', models.TextField(verbose_name="Description de l'acteur")),
                ('category', models.CharField(choices=[('VICTIME', 'VICTIM'), ('ACTEUR', 'ACTOR'), ('WITNESS', 'WITNESS')], default=utils.enums.ActorCategoryEnum['WITNESS'], max_length=200)),
                ('whatsapp', models.TextField(verbose_name="Numéro whatsapp de l'Equipe")),
                ('address', models.JSONField(verbose_name='Localisation')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Catégorie de la denonciation')),
            ],
        ),
        migrations.CreateModel(
            name='Denonciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('pictures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/denonciation_audios')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/denonciation_files')),
                ('status', models.CharField(choices=[('EN ATTENTE', 'PENDING'), ('EN COURS', 'IN_PROGESS'), ('REJETTEE', 'REJECTED'), ('TERMINEE', 'COMPLETED')], default=utils.enums.StatutDenoEnum['PENDING'], max_length=200)),
                ('address', models.JSONField(verbose_name='Localisation')),
                ('priority', models.CharField(choices=[('EN COURS', 'IN_PROGESS'), ('DEJA PASSEE', 'PASSED')], default=utils.enums.PriorityDenoEnum['PASSED'], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(related_name='actors', to='denonciationapp.Actor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='denonciationapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Denonciator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.JSONField(verbose_name='Localisation')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.TextField(verbose_name="Description de l'Equipe")),
                ('contact', models.TextField(verbose_name="contact de l'Equipe")),
                ('whatsapp', models.TextField(verbose_name="Numéro whatsapp de l'Equipe")),
                ('address', models.JSONField(verbose_name='Localisation')),
                ('responsable', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EN ATTENTE', 'PENDING'), ('EN COURS', 'IN_PROGESS'), ('TERMINEE', 'COMPLETED')], default=utils.enums.EtapeStatutEnum['PENDING'], max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(related_name='step_actors', to='denonciationapp.Actor')),
                ('denonciation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='denonciationapp.denonciation')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ARTICLE', 'ARTICLE'), ('ACTUALITE', 'ACTUALITE'), ('DECRET', 'DECRET'), ('DROITS', 'DROITS'), ('RESOLUTION', 'RESOLUTION'), ('INFORMATION', 'INFORMATION')], default=utils.enums.TypePublishEnumEnum['ACTUALITE'], max_length=200)),
                ('content', models.TextField(verbose_name='Description de la publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu de la publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='denonciationapp.publication')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='denonciationapp.denonciator')),
            ],
        ),
        migrations.AddField(
            model_name='denonciation',
            name='denonciator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='denonciationapp.denonciator'),
        ),
        migrations.AddField(
            model_name='denonciation',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='denonciationapp.team'),
        ),
    ]
