# Generated by Django 3.2 on 2023-03-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
